avoid wget to build kernel and busybox, use local paths
Signed-off-by: Ronan Abhamon <ronan.abhamon@vates.fr>

diff --git a/initrd/make-initrd b/initrd/make-initrd
--- a/initrd/make-initrd
+++ b/initrd/make-initrd
@@ -1,7 +1,12 @@
 #!/bin/bash
 
+busybox_path="$1"
+if [ -z "$busybox_path" ]; then
+    echo "Cannot make initrd, path is empty." >&2
+    exit 1
+fi
+
 base="`pwd`/initrd"
-builddir="$base"/build
 outpath="$base"/out
 tmpdir=`mktemp -d`
 tmpfile=`mktemp`
@@ -9,34 +14,15 @@ initrd=$outpath/initrd
 init="$base"/init-initrd
 rm -rf $tmpdir
 
+busybox_src_config="$base"/busybox.config
+busybox="$busybox_path/busybox"
 
-if test -z "$busybox"
-then
-    busybox_version=1.32.0
-    busybox_name=busybox-$busybox_version
-    busybox_tarball="$busybox_name".tar.bz2
-    busybox_url="https://busybox.net/downloads/""$busybox_tarball"
-    busybox_src_config="$base"/busybox.config
-    busybox_image="$builddir"/"$busybox_name"/busybox
+rm -rf $outpath
+mkdir -p $outpath
 
-    rm -rf $outpath
-    mkdir -p $outpath
-    mkdir -p $builddir
-
-    if [[ ! -f $builddir/$busybox_tarball ]]
-    then
-        wget --no-check-certificate -O $builddir/$busybox_tarball --tries=20 $busybox_url
-    fi
-    if [[ ! -d $builddir/$busybox_name ]]
-    then
-        tar --extract --bzip2 --touch --file="$builddir/$busybox_tarball" --directory="$builddir"
-    fi
-    cd $builddir/$busybox_name
-    cp $busybox_src_config .config
-    make -j "$(getconf _NPROCESSORS_ONLN)"
-    export busybox="$busybox_image"
-fi
-
+cd $busybox_path
+cp $busybox_src_config .config
+make -j "$(getconf _NPROCESSORS_ONLN)"
 
 mkdir -p $tmpdir/bin
 mkdir -p $tmpdir/sbin
diff --git a/kernel/make-kernel b/kernel/make-kernel
--- a/kernel/make-kernel
+++ b/kernel/make-kernel
@@ -1,5 +1,11 @@
 #!/bin/bash -x
 
+kernel_path="$1"
+if [ -z "$kernel_path" ]; then
+    echo "Cannot make kernel, path is empty." >&2
+    exit 1
+fi
+
 if [[ $ARCH = "x86"  ]]
 then
     image="bzImage"
@@ -13,36 +19,16 @@ fi
 
 kernel_stuffdir=`readlink -f kernel`
 kernel_outpath=$kernel_stuffdir/out
-kernel_builddir=$kernel_stuffdir/build
 kernel_out=$kernel_outpath/kernel
 
-kernel_version=5.4
-kernel_name=linux-$kernel_version
-kernel_tarball="$kernel_name".tar.xz
-kernel_url=https://www.kernel.org/pub/linux/kernel/v5.x/"$kernel_tarball"
 kernel_src_config="$kernel_stuffdir"/cutdown-config."$ARCH"
 kernel_patchesdir="$kernel_stuffdir"/patches
-kernel_image="$kernel_builddir"/"$kernel_name"/arch/"$ARCH"/boot/"$image"
-
+kernel_image="$kernel_path"/arch/"$ARCH"/boot/"$image"
 
 rm -rf $kernel_outpath
 mkdir -p $kernel_outpath
-mkdir -p $kernel_builddir
 
-if [[ ! -f $kernel_builddir/$kernel_tarball ]]
-then
-    wget -O $kernel_builddir/$kernel_tarball --tries=20 $kernel_url
-fi
-if [[ ! -d $kernel_builddir/$kernel_name ]]
-then
-    tar --extract --xz --touch --file="$kernel_builddir/$kernel_tarball" --directory="$kernel_builddir"
-    cd $kernel_builddir/$kernel_name
-    for i in $kernel_patchesdir/*
-    do
-        patch -p1 < $i
-    done
-fi
-cd $kernel_builddir/$kernel_name
+cd $kernel_path
 cp $kernel_src_config .config
 make -j "$(getconf _NPROCESSORS_ONLN)" $image
 
